import {MigrationInterface, QueryRunner} from "typeorm";

export class UpdateTimeStamps1590790854052 implements MigrationInterface {
    name = 'UpdateTimeStamps1590790854052'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `user_meta` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `isReminder`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `createdAt`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `updatedAt`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `deletedAt`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `is_reminder` tinyint NULL DEFAULT 0", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `deleted_at` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_7acfebc1c4dab180b06c83c66b2`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `course_users` DROP FOREIGN KEY `FK_ec0b6388e3b40c292c8ae1d2f07`", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Unique user ID to identify a single unique user'", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `userMetaId` `userMetaId` int UNSIGNED NULL", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP FOREIGN KEY `FK_3a03a080ce47c9968957da33f08`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `course_users` DROP FOREIGN KEY `FK_32e114cc1e4199c7de081e092a1`", undefined);
        await queryRunner.query("ALTER TABLE `course` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `course` CHANGE `courseMetaId` `courseMetaId` int UNSIGNED NULL", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP FOREIGN KEY `FK_ff3c95aaa00079d9ec5341343ee`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `lesson` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `lesson` CHANGE `lessonMetaId` `lessonMetaId` int UNSIGNED NULL", undefined);
        await queryRunner.query("ALTER TABLE `message` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `message` CHANGE `type` `type` tinyint UNSIGNED NOT NULL DEFAULT 0", undefined);
        await queryRunner.query("ALTER TABLE `notification` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `course_users` CHANGE `userId` `userId` int UNSIGNED NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `course_users` CHANGE `courseId` `courseId` int UNSIGNED NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_7acfebc1c4dab180b06c83c66b2` FOREIGN KEY (`userMetaId`) REFERENCES `user_meta`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD CONSTRAINT `FK_3a03a080ce47c9968957da33f08` FOREIGN KEY (`courseMetaId`) REFERENCES `course_meta`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD CONSTRAINT `FK_ff3c95aaa00079d9ec5341343ee` FOREIGN KEY (`lessonMetaId`) REFERENCES `lesson_meta`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `course_users` ADD CONSTRAINT `FK_ec0b6388e3b40c292c8ae1d2f07` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `course_users` ADD CONSTRAINT `FK_32e114cc1e4199c7de081e092a1` FOREIGN KEY (`courseId`) REFERENCES `course`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `course_users` DROP FOREIGN KEY `FK_32e114cc1e4199c7de081e092a1`", undefined);
        await queryRunner.query("ALTER TABLE `course_users` DROP FOREIGN KEY `FK_ec0b6388e3b40c292c8ae1d2f07`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP FOREIGN KEY `FK_ff3c95aaa00079d9ec5341343ee`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP FOREIGN KEY `FK_3a03a080ce47c9968957da33f08`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_7acfebc1c4dab180b06c83c66b2`", undefined);
        await queryRunner.query("ALTER TABLE `course_users` CHANGE `courseId` `courseId` int(10) UNSIGNED NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `course_users` CHANGE `userId` `userId` int(10) UNSIGNED NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `notification` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `message` CHANGE `type` `type` tinyint(3) UNSIGNED NOT NULL DEFAULT '0'", undefined);
        await queryRunner.query("ALTER TABLE `message` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `lesson` CHANGE `lessonMetaId` `lessonMetaId` int(10) UNSIGNED NULL", undefined);
        await queryRunner.query("ALTER TABLE `lesson` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD CONSTRAINT `FK_ff3c95aaa00079d9ec5341343ee` FOREIGN KEY (`lessonMetaId`) REFERENCES `lesson_meta`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `course` CHANGE `courseMetaId` `courseMetaId` int(10) UNSIGNED NULL", undefined);
        await queryRunner.query("ALTER TABLE `course` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `course_users` ADD CONSTRAINT `FK_32e114cc1e4199c7de081e092a1` FOREIGN KEY (`courseId`) REFERENCES `course`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD CONSTRAINT `FK_3a03a080ce47c9968957da33f08` FOREIGN KEY (`courseMetaId`) REFERENCES `course_meta`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `userMetaId` `userMetaId` int(10) UNSIGNED NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Unique user ID to identify a single unique user'", undefined);
        await queryRunner.query("ALTER TABLE `course_users` ADD CONSTRAINT `FK_ec0b6388e3b40c292c8ae1d2f07` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_7acfebc1c4dab180b06c83c66b2` FOREIGN KEY (`userMetaId`) REFERENCES `user_meta`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `is_reminder`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `message` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `lesson` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `course` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` DROP COLUMN `deleted_at`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` DROP COLUMN `updated_at`", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` DROP COLUMN `created_at`", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `isReminder` tinyint NULL DEFAULT '0'", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `message` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `lesson_meta` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `course_meta` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` ADD `deletedAt` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` ADD `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
        await queryRunner.query("ALTER TABLE `user_meta` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", undefined);
    }

}
