import React from "react";
import DashboardLayout from "../../src/components/layouts/DashboardLayout";

const Lessons: React.FC = () => (
  <DashboardLayout>
    <h1>Dashboard Home</h1>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique ut, veniam a alias qui reiciendis ea? Aliquid cumque nihil tenetur saepe veniam repudiandae beatae voluptatem. Quos dignissimos aliquam nam rerum itaque quo quam? Officia, voluptates possimus. Libero nesciunt, repudiandae, excepturi perferendis amet magni nisi ut, unde sunt totam alias earum aliquid quasi neque tempora porro corporis! Temporibus earum esse voluptatem beatae nobis quibusdam illo voluptates veritatis corporis aut rerum dolores nisi, excepturi, soluta architecto voluptate placeat. Voluptate maxime aut laboriosam nobis a mollitia et quo molestiae earum, at culpa laborum. Non natus iusto exercitationem sapiente eveniet eum fugiat facere et!</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique ut, veniam a alias qui reiciendis ea? Aliquid cumque nihil tenetur saepe veniam repudiandae beatae voluptatem. Quos dignissimos aliquam nam rerum itaque quo quam? Officia, voluptates possimus. Libero nesciunt, repudiandae, excepturi perferendis amet magni nisi ut, unde sunt totam alias earum aliquid quasi neque tempora porro corporis! Temporibus earum esse voluptatem beatae nobis quibusdam illo voluptates veritatis corporis aut rerum dolores nisi, excepturi, soluta architecto voluptate placeat. Voluptate maxime aut laboriosam nobis a mollitia et quo molestiae earum, at culpa laborum. Non natus iusto exercitationem sapiente eveniet eum fugiat facere et!</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique ut, veniam a alias qui reiciendis ea? Aliquid cumque nihil tenetur saepe veniam repudiandae beatae voluptatem. Quos dignissimos aliquam nam rerum itaque quo quam? Officia, voluptates possimus. Libero nesciunt, repudiandae, excepturi perferendis amet magni nisi ut, unde sunt totam alias earum aliquid quasi neque tempora porro corporis! Temporibus earum esse voluptatem beatae nobis quibusdam illo voluptates veritatis corporis aut rerum dolores nisi, excepturi, soluta architecto voluptate placeat. Voluptate maxime aut laboriosam nobis a mollitia et quo molestiae earum, at culpa laborum. Non natus iusto exercitationem sapiente eveniet eum fugiat facere et!</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique ut, veniam a alias qui reiciendis ea? Aliquid cumque nihil tenetur saepe veniam repudiandae beatae voluptatem. Quos dignissimos aliquam nam rerum itaque quo quam? Officia, voluptates possimus. Libero nesciunt, repudiandae, excepturi perferendis amet magni nisi ut, unde sunt totam alias earum aliquid quasi neque tempora porro corporis! Temporibus earum esse voluptatem beatae nobis quibusdam illo voluptates veritatis corporis aut rerum dolores nisi, excepturi, soluta architecto voluptate placeat. Voluptate maxime aut laboriosam nobis a mollitia et quo molestiae earum, at culpa laborum. Non natus iusto exercitationem sapiente eveniet eum fugiat facere et!</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique ut, veniam a alias qui reiciendis ea? Aliquid cumque nihil tenetur saepe veniam repudiandae beatae voluptatem. Quos dignissimos aliquam nam rerum itaque quo quam? Officia, voluptates possimus. Libero nesciunt, repudiandae, excepturi perferendis amet magni nisi ut, unde sunt totam alias earum aliquid quasi neque tempora porro corporis! Temporibus earum esse voluptatem beatae nobis quibusdam illo voluptates veritatis corporis aut rerum dolores nisi, excepturi, soluta architecto voluptate placeat. Voluptate maxime aut laboriosam nobis a mollitia et quo molestiae earum, at culpa laborum. Non natus iusto exercitationem sapiente eveniet eum fugiat facere et!</p>
  </DashboardLayout>
);

export default Lessons;
